/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';

// Unique cache namespace per build version
const CACHE_NAME = `portal-quran-v${version}`;

// Essential static assets generated by SvelteKit and in static directory
const ASSETS_TO_CACHE = [
	...build,
	...files.filter((file) => !file.startsWith('/.') && file !== '/robots.txt')
];

// Unhashed root assets that can change across deployments (logo, icons, manifest)
const ROOT_ASSETS = ['/logo.png', '/favicon.png', '/apple-touch-icon.png', '/icon-192.png', '/icon-512.png', '/manifest.webmanifest', '/manifest.json'];

self.addEventListener('install', (event) => {
	// Pre-cache all build assets in the new cache
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS_TO_CACHE))
			.then(() => {
				// Allow new service worker to prepare without waiting if skipWaiting triggered
			})
	);
});

self.addEventListener('activate', (event) => {
	// Clean up all obsolete caches from older versions
	event.waitUntil(
		caches
			.keys()
			.then((keys) =>
				Promise.all(
					keys.map((key) => {
						if (key !== CACHE_NAME) {
							return caches.delete(key);
						}
					})
				)
			)
			.then(() => self.clients.claim())
	);
});

// Listen for client messages (e.g. SKIP_WAITING from update prompt or auto-update)
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		self.skipWaiting();
	} else if (event.data && event.data.type === 'GET_VERSION') {
		event.ports?.[0]?.postMessage({ version, cacheName: CACHE_NAME });
	}
});

self.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);

	// Only handle HTTP/HTTPS GET requests
	if (!url.protocol.startsWith('http') || event.request.method !== 'GET') {
		return;
	}

	// Bypass external APIs, audio streaming, Supabase, version.json, and dynamic Quran APIs to keep cache clean & fast
	if (
		url.pathname === '/version.json' ||
		url.pathname.endsWith('.mp3') ||
		url.hostname.includes('supabase.co') ||
		url.hostname.includes('everyayah.com') ||
		url.hostname.includes('qurancdn.com') ||
		url.hostname.includes('api.quran.com') ||
		url.hostname.includes('api.myquran.com') ||
		url.hostname.includes('unsplash.com')
	) {
		return;
	}

	// 1. Navigation requests (HTML pages / routes) -> Network First with Cache Fallback
	if (event.request.mode === 'navigate') {
		event.respondWith(
			fetch(event.request)
				.then((response) => {
					if (response && response.status === 200) {
						const responseClone = response.clone();
						caches.open(CACHE_NAME).then((cache) => {
							cache.put(event.request, responseClone);
						});
					}
					return response;
				})
				.catch(async () => {
					const cachedResponse = await caches.match(event.request);
					if (cachedResponse) {
						return cachedResponse;
					}
					const fallbackHome = await caches.match('/');
					if (fallbackHome) {
						return fallbackHome;
					}
					return new Response('Portal Qur\'an sedang offline', {
						status: 503,
						statusText: 'Service Unavailable',
						headers: { 'Content-Type': 'text/plain; charset=utf-8' }
					});
				})
		);
		return;
	}

	// 2. Dynamic Root Assets (Logo, icons, manifest) -> Network First with Cache Fallback
	// This ensures logo or branding changes take effect immediately on next fetch
	if (ROOT_ASSETS.includes(url.pathname)) {
		event.respondWith(
			fetch(event.request)
				.then((networkResponse) => {
					if (networkResponse && networkResponse.status === 200) {
						const responseClone = networkResponse.clone();
						caches.open(CACHE_NAME).then((cache) => {
							cache.put(event.request, responseClone);
						});
					}
					return networkResponse;
				})
				.catch(() => caches.match(event.request))
		);
		return;
	}

	// 3. Immutable/Hashed Build Assets (JS, CSS chunks) -> Cache First with Network Fallback
	event.respondWith(
		caches.match(event.request).then((cachedResponse) => {
			if (cachedResponse) {
				return cachedResponse;
			}

			return fetch(event.request).then((networkResponse) => {
				if (networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic') {
					const responseClone = networkResponse.clone();
					caches.open(CACHE_NAME).then((cache) => {
						cache.put(event.request, responseClone);
					});
				}
				return networkResponse;
			});
		})
	);
});
